In [6]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("../dataset/cat_2_dataset.csv")

In [10]:
data = np.array(df)

In [12]:
print(data)

[[ 1  2  5 70  3  4 48]
 [ 2  3  6 80  4  3 55]
 [ 3  4  4 60  2  5 52]
 [ 4  5  5 90  5  2 65]
 [ 5  1  6 50  1  6 40]
 [ 6  6  4 95  5  1 70]
 [ 7  3  5 75  3  4 50]
 [ 8  2  4 55  2  5 45]
 [ 9  7  3 98  5  1 80]
 [10  4  6 85  4  3 60]]


In [14]:
# Extract features (X) and target (y)
X = data[:, :-1]
y = data[:,-1]

In [16]:
# Convert to bipolar values
median_X = np.median(X, axis=0)
X_bipolar = np.where(X > median_X, 1, -1)

In [18]:
# Get the y median and bypolar
median_y = np.median(y)
y_bipolar = np.where(y > 50, 1,-1)

In [ ]:
# Initial Weights
weights = np.zeros(X.shape[1])
