In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("../dataset/cat_2_dataset.csv")

In [7]:
data = np.array(df)

In [9]:
print(data)

[[ 1  2  5 70  3  4 48]
 [ 2  3  6 80  4  3 55]
 [ 3  4  4 60  2  5 52]
 [ 4  5  5 90  5  2 65]
 [ 5  1  6 50  1  6 40]
 [ 6  6  4 95  5  1 70]
 [ 7  3  5 75  3  4 50]
 [ 8  2  4 55  2  5 45]
 [ 9  7  3 98  5  1 80]
 [10  4  6 85  4  3 60]]


In [11]:
# Extract features (X) and target (y)
X = data[:, :-1]
y = data[:,-1]

In [25]:
# Calculate medians for X
medians = np.median(X, axis=0)

In [27]:
# Convert X to bipolar
X_bipolar = np.where(X > medians, 1, -1)

In [29]:
# Convert y bipolar
#median_y = np.median(y)
y_bipolar = np.where(y > 50, 1,-1)

In [31]:
# Initial Weights
weights = np.zeros(X_bipolar.shape[1])


In [33]:
# Update weights over the first 3 samples
for i in range(3):
    weights = weights * X_bipolar[i] * y_bipolar[i]

In [41]:
# Predict sign for input [1,-1,1,-1,1]
input_data = np.array([1,-1,1,-1,1])
if input_data.shape[0] != weights.shape[0]:
    raise ValueError(f'Input data has {input_data.shape[0]} features, but weights have {weights.shape[0]}')
prediction = np.sign(np.dot(input_data, weights))

ValueError: Input data has 5 features, but weights have 6